In [4]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

import joblib

In [5]:
customers = pd.read_csv("customers.csv")

customers.head()

,CustomerID,Age,Gender,Occupation,MonthlyIncome,Region,Branch,FCYAccount,ETBAccount,MobileBanking,InternetBanking,RemittanceCount,TotalRemittanceUSD,AverageTransactionUSD,FCYPurchaseUSD,LastTransactionDays,ExistingProducts,LeadStatus
0,100001,59,Female,Business Owner,71321,Addis Ababa,Adama,Yes,Yes,Yes,No,5,5145,857.50,2167,166,2,0
1,100002,49,Male,Merchant,144028,Amhara,CMC,No,Yes,No,No,8,8416,935.11,1779,150,5,0
2,100003,35,Female,Teacher,86131,Addis Ababa,Bole,No,Yes,Yes,No,5,5925,987.50,2163,363,2,0
3,100004,63,Female,Merchant,37963,Tigray,Megenagna,Yes,Yes,No,Yes,5,3815,635.83,1569,343,3,0
4,100005,28,Male,Private Employee,113757,Amhara,CMC,No,Yes,No,No,3,3033,758.25,1615,68,3,0

In [ ]:

customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   CustomerID             500 non-null    int64
 1   Age                    500 non-null    int64
 2   Gender                 500 non-null    object
 3   Occupation             500 non-null    object
 4   MonthlyIncome          500 non-null    int64
 5   Region                 500 non-null    object
 6   Branch                 500 non-null    object
 7   FCYAccount             500 non-null    object
 8   ETBAccount             500 non-null    object
 9   MobileBanking          500 non-null    object
 10  InternetBanking        500 non-null    object
 11  RemittanceCount        500 non-null    int64
 12  TotalRemittanceUSD     500 non-null    int64
 13  AverageTransactionUSD  500 non-null    float64
 14  FCYPurchaseUSD         500 non-null    int64
 15  LastTransactionDays    500 non-null    int64
 16  ExistingProducts       500 non-null    int64
 17  LeadStatus             500 non-null    int64
dtypes: float64(1), int64(9), object(8)
memory usage: 70.4+ KB

In [ ]:
#Check Missing Values
customers.isnull().sum()

CustomerID               0
Age                      0
Gender                   0
Occupation               0
MonthlyIncome            0
Region                   0
Branch                   0
FCYAccount               0
ETBAccount               0
MobileBanking            0
InternetBanking          0
RemittanceCount          0
TotalRemittanceUSD       0
AverageTransactionUSD    0
FCYPurchaseUSD           0
LastTransactionDays      0
ExistingProducts         0
LeadStatus               0
dtype: int64

In [ ]:
#Remove Duplicate Records
customers = customers.drop_duplicates()

In [9]:
customers.shape

(500, 18)

In [ ]:
#Convert Yes/No Columns
binary_map = {
    "Yes":1,
    "No":0
}

In [11]:
customers["FCYAccount"] = customers["FCYAccount"].map(binary_map)

customers["ETBAccount"] = customers["ETBAccount"].map(binary_map)

customers["MobileBanking"] = customers["MobileBanking"].map(binary_map)

customers["InternetBanking"] = customers["InternetBanking"].map(binary_map)

In [12]:
customers.head()

,CustomerID,Age,Gender,Occupation,MonthlyIncome,Region,Branch,FCYAccount,ETBAccount,MobileBanking,InternetBanking,RemittanceCount,TotalRemittanceUSD,AverageTransactionUSD,FCYPurchaseUSD,LastTransactionDays,ExistingProducts,LeadStatus
0,100001,59,Female,Business Owner,71321,Addis Ababa,Adama,1,1,1,0,5,5145,857.50,2167,166,2,0
1,100002,49,Male,Merchant,144028,Amhara,CMC,0,1,0,0,8,8416,935.11,1779,150,5,0
2,100003,35,Female,Teacher,86131,Addis Ababa,Bole,0,1,1,0,5,5925,987.50,2163,363,2,0
3,100004,63,Female,Merchant,37963,Tigray,Megenagna,1,1,0,1,5,3815,635.83,1569,343,3,0
4,100005,28,Male,Private Employee,113757,Amhara,CMC,0,1,0,0,3,3033,758.25,1615,68,3,0

In [ ]:
#Encode Gender
gender_encoder = LabelEncoder()

In [14]:
customers["Gender"] = gender_encoder.fit_transform(
    customers["Gender"]
)

In [ ]:
#Encode Occupation
occupation_encoder = LabelEncoder()

customers["Occupation"] = occupation_encoder.fit_transform(
    customers["Occupation"]
)

In [ ]:
#Encode Region
region_encoder = LabelEncoder()

customers["Region"] = region_encoder.fit_transform(
    customers["Region"]
)

In [ ]:
#Encode Branch
branch_encoder = LabelEncoder()

customers["Branch"] = branch_encoder.fit_transform(
    customers["Branch"]
)

In [18]:
customers.head()

,CustomerID,Age,Gender,Occupation,MonthlyIncome,Region,Branch,FCYAccount,ETBAccount,MobileBanking,InternetBanking,RemittanceCount,TotalRemittanceUSD,AverageTransactionUSD,FCYPurchaseUSD,LastTransactionDays,ExistingProducts,LeadStatus
0,100001,59,0,0,71321,0,0,1,1,1,0,5,5145,857.50,2167,166,2,0
1,100002,49,1,5,144028,1,3,0,1,0,0,8,8416,935.11,1779,150,5,0
2,100003,35,0,9,86131,0,2,0,1,1,0,5,5925,987.50,2163,363,2,0
3,100004,63,0,5,37963,7,5,1,1,0,1,5,3815,635.83,1569,343,3,0
4,100005,28,1,7,113757,1,3,0,1,0,0,3,3033,758.25,1615,68,3,0

In [ ]:
#Separate Features and Target
y = customers["LeadStatus"]

In [20]:
X = customers.drop(
    columns=["LeadStatus"]
)

In [21]:
print(X.shape)

print(y.shape)

(500, 17)
(500,)

In [ ]:
#Train/Test Split
X_train,X_test,y_train,y_test = train_test_split(

X,

y,

test_size=0.20,

random_state=42,

stratify=y

)

In [23]:
print(X_train.shape)

print(X_test.shape)

(400, 17)
(100, 17)

In [ ]:
#Train/Test Split
numeric_columns = [

"Age",

"MonthlyIncome",

"RemittanceCount",

"TotalRemittanceUSD",

"AverageTransactionUSD",

"FCYPurchaseUSD",

"LastTransactionDays",

"ExistingProducts"

]

In [25]:
scaler = StandardScaler()

In [26]:
X_train[numeric_columns] = scaler.fit_transform(
    X_train[numeric_columns]
)

In [27]:
X_test[numeric_columns] = scaler.transform(
    X_test[numeric_columns]
)

In [ ]:
#Verify Scaling
X_train.head()

,CustomerID,Age,Gender,Occupation,MonthlyIncome,Region,Branch,FCYAccount,ETBAccount,MobileBanking,InternetBanking,RemittanceCount,TotalRemittanceUSD,AverageTransactionUSD,FCYPurchaseUSD,LastTransactionDays,ExistingProducts
329,100330,-0.250402,1,4,1.259802,5,1,0,1,1,1,1.199558,-0.484944,-1.349963,-0.351473,-0.051566,-0.761623
148,100149,-0.890636,1,8,-0.981270,6,4,0,1,1,0,0.078476,-0.326800,-0.512690,0.558322,1.315401,-0.761623
44,100045,-1.530870,1,2,0.357270,4,1,1,1,0,1,-2.163689,-1.719814,-1.453512,-1.300029,-0.941030,0.652063
35,100036,1.528024,1,5,-1.040972,0,4,0,1,1,0,-1.416300,-1.174348,-0.585423,-0.521176,0.865988,-0.761623
111,100112,1.172339,1,0,-0.099512,5,6,0,1,1,1,0.078476,-0.787400,-1.196504,-1.151800,1.652462,1.358905

In [ ]:
#Save Encoders
joblib.dump(
    gender_encoder,
    "gender_encoder.pkl"
)

joblib.dump(
    occupation_encoder,
    "occupation_encoder.pkl"
)

joblib.dump(
    region_encoder,
    "region_encoder.pkl"
)

joblib.dump(
    branch_encoder,
    "branch_encoder.pkl"
)

['branch_encoder.pkl']

In [ ]:
#Save Scaler
joblib.dump(
    scaler,
    "scaler.pkl"
)

['scaler.pkl']

In [ ]:
#Save Processed Data
X_train.to_csv(
    "X_train.csv",
    index=False
)

y_train.to_csv(
    "y_train.csv",
    index=False
)

In [32]:
X_test.to_csv(
    "X_test.csv",
    index=False
)

y_test.to_csv(
    "y_test.csv",
    index=False
)

In [ ]:
#Verify Files
import os

files = [

"X_train.csv",

"X_test.csv",

"y_train.csv",

"y_test.csv",

"scaler.pkl",

"gender_encoder.pkl",

"occupation_encoder.pkl",

"region_encoder.pkl",

"branch_encoder.pkl"

]

for f in files:

    print(f, os.path.exists(f))

X_train.csv True
X_test.csv True
y_train.csv True
y_test.csv True
scaler.pkl True
gender_encoder.pkl True
occupation_encoder.pkl True
region_encoder.pkl True
branch_encoder.pkl True

In [35]:
#Final Check
print("="*50)

print("Preprocessing Completed")

print("="*50)

print("Training Data :", X_train.shape)

print("Testing Data  :", X_test.shape)

print("Features      :", X_train.columns.tolist())

print("="*50)

==================================================
Preprocessing Completed
==================================================
Training Data : (400, 17)
Testing Data  : (100, 17)
Features      : ['CustomerID', 'Age', 'Gender', 'Occupation', 'MonthlyIncome', 'Region', 'Branch', 'FCYAccount', 'ETBAccount', 'MobileBanking', 'InternetBanking', 'RemittanceCount', 'TotalRemittanceUSD', 'AverageTransactionUSD', 'FCYPurchaseUSD', 'LastTransactionDays', 'ExistingProducts']
==================================================